# Generated by Django 4.2.4 on 2023-08-03 00:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=25)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'horario_carreras',
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('posicion', models.IntegerField()),
            ],
            options={
                'db_table': 'horario_periodos',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=25)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('habilitado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'horario_profesores',
            },
        ),
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=25)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'horario_salones',
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion', models.IntegerField()),
            ],
            options={
                'db_table': 'horario_variables',
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=25)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.carreras')),
            ],
            options={
                'db_table': 'horario_materias',
            },
        ),
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_asignacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.materias')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.periodos')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.profesores')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.salones')),
            ],
            options={
                'db_table': 'horario_asignaciones',
            },
        ),
    ]
