# Generated by Django 4.2.4 on 2023-08-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciones',
            name='alerta',
            field=models.BooleanField(default=False),
        ),
    ]
