# Generated by Django 4.2.4 on 2023-08-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO horario_areas (id, codigo, nombre) VALUES (1, 'BASICA',     'Area Basica');"),
        migrations.RunSQL("INSERT INTO horario_areas (id, codigo, nombre) VALUES (2, 'PROFESIONAL', 'Area Profesional');"),
    ]
