# Generated by Django 4.2.4 on 2023-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_auto_20230825_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='semestre',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
