# Generated by Django 4.2.4 on 2023-08-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_materias_semestre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilitacion',
            new_name='Habilitaciones',
        ),
        migrations.AlterModelTable(
            name='habilitaciones',
            table='horario_habilitaciones',
        ),
    ]
