# Generated by Django 4.2.4 on 2023-08-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0004_rename_habilitacion_habilitaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciones',
            name='error',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
